name: Pull check
on:
  pull_request:
  push:
    branches: master

jobs:

  code-check:
    name: Code check
    runs-on: ubuntu-latest
    steps:

    - name: Unit testing
      uses: bgdshka/echart-component/.github/actions/unit-and-shapshots@master

    - name: Screenshots
      uses: bgdshka/echart-component/.github/actions/screenshots@master
